<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        //  (1) 当使用 promise 的 then 链式调用时, 可以在最后指定失败的回调, 
        // (2) 前面任何操作出了异常, 都会传到最后失败的回调中处理 一旦有失败则 失败后面的不再显示
         let p = new Promise((resove,reject)=>resove('成功啦'))
         p.then(value=>{
            console.log(value)
            return 123
            })
            .then(value=>{console.log(value) 
                return  new Promise((resove,reject)=>reject('没有了')) 
            })
            .then(value=>{console.log(value) 
                return  new Promise((resove,reject)=>resove('success')) 
            })
            .then(value=>console.log(value))
            .catch(reason=>console.warn(reason))
    </script>
</body>
</html>